name: build_go

on:
  push:
    paths:
      - 'source/**'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v3
      with:
        python-version: '3.9'
    - name: build go
      run: go build source/hello/main.go
    - name: run go
      run: ./main
      
      
