name: build_go

on:
  push:
    paths:
      - 'source/**'
      - '.github/workflows/build_go.yml'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v3
      with:
        python-version: '3.9'
    - name: Build go
      run: go build source/hello/main.go
    - name: Run go
      run: ./main
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: linux
        path: ./main
    
      
      
      
